# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-certificate
  namespace: jenkins
spec:
  secretName: jenkins-tls
  privateKey:
    rotationPolicy: Always
  commonName: jenkins.huemmer.cloud
  dnsNames:
    - jenkins.huemmer.cloud
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer